version: '3.9'
services:
  watering-web-frontend:
    build: ./frontend
    ports:
      - "80:80"
    deploy:
      placement:
        constraints:
            - node.role == worker
            - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network
  
  watering-web-backend:
    build: ./backend
    ports:
      - "8081:8081"
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network